### ISSUE TITLE
Rake:setup

### ISSUE THREAD

**Issue by Grenmyr** [vl222cu/1DV450_vl222cu_API#1]
SyntaxError: /home/dav/Hämtningar/1DV450_vl222cu_API-1.0/db/seeds.rb:9: syntax error, unexpected tIDENTIFIER, expecting ')'
...ate(username: "Tingeling" email: "ting@ling.com", password: ...
...                               ^

Du har glömt lägga in "," på flera ställen i din seeds.rb fil. Det går snabbt att fixa, dock fungerar inte seeds om det ej fixas. Jag la in det själv dock och då funkar seed filen, men du kanske vill fixa i ditt repo.

**Comment by vl222cu** [comment]
Hej och tack snälla för infot!! Hade nog lite bråttom där för att få klart allt till deadline, ber så mycket om ursäkt, va bra att du fixade till det :) Jag rättar till det direkt här :) Du får höra av dig om det är något mer som inte funkar!

Hälsningar Vivi
