### ISSUE TITLE
Beröm Issue :-)

### ISSUE THREAD

**Issue by Grenmyr** [vl222cu/1DV450_vl222cu_API#3]
Detta blir lite feedback på din kodkvalite :+1: 

Bra installationsguide!!

Dina kontroller är fantastiska, lättlästa och väldigt lite Dry.

Modellerna är kanon, validering där det behövs. Creator lösenord ej sparat i klartext, jättebra.

Din struktur på Api är också jättebra, lättnavigerat och förutom https://github.com/vl222cu/1DV450_vl222cu_API/issues/2 issue, så verkar felhantering vara kanonbra. Du har även använt HATEOAS.

Med beröm godkänt. Lycka till med Angular appen!
David Grenmyr

**Comment by vl222cu** [comment]
Ååååh vilken värmande feedback David!!! :) Vad glad jag blir!!! :D TACK TACK!!! Jag ska absolut ta o kika över Issue 2 och se vad som behöver fixas :) 

Tack snälla! Lycka till du också med Angularappen! :) 

Hälsningar Vivi
